### ISSUE TITLE
Error: Cannot find module './952.js'

### ISSUE THREAD

**Issue by gitakileus** [oceanprotocol/market#1611]
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 375 ms (2442 modules)
Error: Cannot find module './952.js'
Require stack:
- /workspace/Ocean-market/.next/server/webpack-runtime.js
- /workspace/Ocean-market/.next/server/pages/_document.js
- /workspace/Ocean-market/node_modules/next/dist/server/require.js
- /workspace/Ocean-market/node_modules/next/dist/server/next-server.js
- /workspace/Ocean-market/node_modules/next/dist/server/next.js
- /workspace/Ocean-market/node_modules/next/dist/server/lib/start-server.js
- /workspace/Ocean-market/node_modules/next/dist/cli/next-dev.js
- /workspace/Ocean-market/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/workspace/Ocean-market/node_modules/next/dist/build/webpack/require-hook.js:182:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.__webpack_require__.f.require (/workspace/Ocean-market/.next/server/webpack-runtime.js:227:28)
    at /workspace/Ocean-market/.next/server/webpack-runtime.js:149:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (/workspace/Ocean-market/.next/server/webpack-runtime.js:148:67)
    at Array.map (<anonymous>)
    at Function.__webpack_require__.X (/workspace/Ocean-market/.next/server/webpack-runtime.js:186:22)
    at /workspace/Ocean-market/.next/server/pages/_document.js:810:47
    at Object.<anonymous> (/workspace/Ocean-market/.next/server/pages/_document.js:813:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/Ocean-market/.next/server/webpack-runtime.js',
    '/workspace/Ocean-market/.next/server/pages/_document.js',
    '/workspace/Ocean-market/node_modules/next/dist/server/require.js',
    '/workspace/Ocean-market/node_modules/next/dist/server/next-server.js',
    '/workspace/Ocean-market/node_modules/next/dist/server/next.js',
    '/workspace/Ocean-market/node_modules/next/dist/server/lib/start-server.js',
    '/workspace/Ocean-market/node_modules/next/dist/cli/next-dev.js',
    '/workspace/Ocean-market/node_modules/next/dist/bin/next'
  ]
}

How to fix it
Please let me know.

**Comment by kremalicious** [comment]
Please make sure `npm install` or `npm install --legacy-peer-deps` succeeds first.

**Comment by gitakileus** [comment]
Thanks very much
