### ISSUE TITLE
Error: Failed to collect page data for /404

### ISSUE THREAD

**Issue by harishgupta** [oceanprotocol/market#1811]
**Describe the bug**

**To Reproduce**
1. Clone github.com/oceanprotocol/market repo
2.  npm i
3. npm start

**Expected**
Should see the local instance of Ocean Marketplace

**Actual**
The following error

wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 679 ms (1923 modules)
error - unhandledRejection: TypeError: Cannot set property Request of #<Object> which has only a getter
    at /home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:529:18
    at /home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:542:5
    at /home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:3:3
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:4:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3-providers-http/lib/index.js:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3-core-requestmanager/lib/index.js:45:19)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3-core/lib/index.js:22:24)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3/lib/index.js:29:12)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/@oceanprotocol/lib/dist/lib.js:1:124)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.@oceanprotocol/lib (/home/ec2-user/ocean/ocean-market/.next/server/pages/_app.js:2010:18)
    at __webpack_require__ (/home/ec2-user/ocean/ocean-market/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/components/@shared/FormInput/InputElement/Provider/index.tsx:17:76)
    at Function.__webpack_require__.a (/home/ec2-user/ocean/ocean-market/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/components/@shared/FormInput/InputElement/Provider/index.tsx:1:21)
error - unhandledRejection: TypeError: Cannot set property Request of #<Object> which has only a getter
    at /home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:529:18
    at /home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:542:5
    at /home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:3:3
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/abortcontroller-polyfill/dist/polyfill-patch-fetch.js:4:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3-providers-http/lib/index.js:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3-core-requestmanager/lib/index.js:45:19)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3-core/lib/index.js:22:24)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/web3/lib/index.js:29:12)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/ec2-user/ocean/ocean-market/node_modules/@oceanprotocol/lib/dist/lib.js:1:124)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.@oceanprotocol/lib (/home/ec2-user/ocean/ocean-market/.next/server/pages/_app.js:2010:18)
    at __webpack_require__ (/home/ec2-user/ocean/ocean-market/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/@utils/ocean.ts:6:76)
    at Object../src/@utils/ocean.ts (/home/ec2-user/ocean/ocean-market/.next/server/pages/_app.js:1276:1)
    at __webpack_require__ (/home/ec2-user/ocean/ocean-market/.next/server/webpack-runtime.js:33:42)

**Comment by kremalicious** [comment]
are you using Node.js v18 or some older version?

**Comment by jamiehewitt15** [comment]
Yeah, this look like it has been caused by using the wrong version of node.js

**Comment by harishgupta** [comment]
Looks like it was related to the node version itself. Thanks !!
