### ISSUE TITLE
Rinkeby Provider not working with market

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#804]
I noticed something weird while testing the market on Rinkeby. After successfully publishing a dataset it says there is "no file info available" for the dataset and when I try to purchase it, I get the error message saying the URL is unavailable.
I was using a simple [url to a csv](https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv) in the test which seems to work fine, and the provider confirmed it was valid while publishing.

![no file data](https://user-images.githubusercontent.com/20739535/130277984-8b24568c-722e-4646-a114-ebc97bc21a55.png)

I have done two tests and the same things happened both times ([1](https://market.oceanprotocol.com/asset/did:op:e5aaA6800e8ea532d106DbcBFdAeb62bfe4aF55D) and [2](https://market.oceanprotocol.com/asset/did:op:5Ce833BA3Bf48421d6B54c9CF688AfEB4DB7A409))

**Comment by jamiehewitt15** [comment]
Comments from @kremalicious copied from slack:

> good find, and it looks like it actually affects all assets. I also can’t see any network connection being done to any provider suggesting we broke that altogether somehow and it’s not even fetching the info

> the no wallet case it is, seems without wallet we don’t fetch any file info. Regardless, with wallet connected I also don’t get file info for your Rinkeby examples

> Basically we can’t rely on config from useOcean cause that’s only there when there is an “Ocean connection” meaning a wallet connected https://github.com/oceanprotocol/market/pull/803

> as for your Rinkeby assets this seems caused by 500 from provider
![image](https://user-images.githubusercontent.com/20739535/130278318-c3b16532-507b-42e5-abf3-3f76f05e43f3.png)
> so it might be simply a problem with Rinkeby provider only :crossed_fingers:

**Comment by jamiehewitt15** [comment]
I've done a text on Robsten and that worked, so for now it seems like this is just affecting Rinkeby

**Comment by mihaisc** [comment]
![image](https://user-images.githubusercontent.com/26000280/130409357-502b6f93-cbd0-406b-99d0-64f5cc8f7e64.png)

**Comment by alexcos20** [comment]
2021-08-23 11:13:13 provider-655c6f4ff5-2bk5t urllib3.connectionpool[11] DEBUG Starting new HTTPS connection (1): aquarius.rinkeby.oceanprotocol.com:443
2021-08-23 11:13:13 provider-655c6f4ff5-2bk5t urllib3.connectionpool[11] DEBUG https://aquarius.rinkeby.oceanprotocol.com:443 "GET //api/v1/aquarius/assets/ddo/did:op:b31e754515C56A6f1701aeBfAB8620F077C7ac8f HTTP/1.1" 404 75
2021-08-23 11:13:13,213 - ocean_provider.myapp - ERROR - Exception on /api/v1/services/fileinfo [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/common/aquarius/aquarius.py", line 203, in _parse_response
    return json.loads(response)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_sieve/validator.py", line 81, in wrapper
    return fn(*args, **kwargs)
  File "/ocean-provider/ocean_provider/routes/consume.py", line 177, in fileinfo
    asset = get_asset_from_metadatastore(get_metadata_url(), did)
  File "/ocean-provider/ocean_provider/utils/basics.py", line 81, in get_asset_from_metadatastore
    return aqua.get_asset_ddo(document_id)
  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/common/aquarius/aquarius.py", line 81, in get_asset_ddo
    parsed_response = _parse_response(response, None)
  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/common/aquarius/aquarius.py", line 207, in _parse_response
    raise ValueError(response.decode("UTF-8"))
ValueError: did:op:b31e754515C56A6f1701aeBfAB8620F077C7ac8f asset DID is not in OceanDB



and this is because:

       - name: AQUARIUS_URL
          value: https://aquarius.rinkeby.oceanprotocol.com/
